import AppKit

/// Решает, можно ли вообще сохранять то, что сейчас в буфере.
///
/// Менеджер буфера, который пишет всё подряд, рано или поздно сохранит пароль от банка
/// открытым текстом. Поэтому фильтр — часть ядра, а не настройка.
struct PrivacyFilter {
    /// Неофициальный, но общепринятый протокол nspasteboard.org: этими маркерами приложения
    /// сообщают менеджерам буфера «не сохраняй». ConcealedType ставят парольные менеджеры
    /// (1Password, Bitwarden, KeePassXC), Transient — софт, кладущий в буфер временное.
    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    var ignoredBundleIDs: Set<String> = []

    func allows(_ pasteboard: NSPasteboard, source: ClipSource?) -> Bool {
        let types = pasteboard.types ?? []

        for marker in [Self.concealed, Self.transient, Self.autoGenerated] where types.contains(marker) {
            Log.clipboard.info("копия пропущена: маркер \(marker.rawValue, privacy: .public)")
            return false
        }

        if let bundleID = source?.bundleID, ignoredBundleIDs.contains(bundleID) {
            Log.clipboard.info("копия пропущена: приложение \(bundleID, privacy: .public) в игнор-листе")
            return false
        }

        return true
    }
}
